language: node_js
node_js:
  - "0.12"

before_install:
    - npm install -g grunt-cli
install:
    - npm install grunt-contrib-uglify --save-dev
    - npm install --save-dev grunt-sass
    - npm install grunt-contrib-sass --save-dev
    - npm install grunt-contrib-watch --save-dev
script: grunt build
